# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68a896d53e595694a8917eddbc390da31e875c5fa6039a63ed04377a26c9a2cd29e004d23a8fba65fa9bfd7d08f6a58964bcba2350530fbef36e93d1e5ad7ad

test:
  secret_key_base: 0a0807021f760acdd947855299670fe52df246b88a4a36ce09ce55e5bbe1832ba83c3df5d7b3c5872df60034bba357d3f3d7fac21b7b3ccce15182c044057a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
